### ISSUE TITLE
Uncollapse "Programming languages" and "Tags" sidebars by default

### ISSUE THREAD

**Issue by nodiscc** [n8225/awesome-selfhosted-gen#1]
I think it would make sense to have the 2 left sidebar blocks un-collapsed by default. This allows quickly filtering the item/seeing at a glance what all the tags/categories are.

 - This might not be needed for programming languages, but for consistency I suggest that both should be un-collapsed by default.
 - I agree this might not ideal on mobile as this displays as the first item (before the list).
 - If you really want to make these sections collapsible, at least put a hint (up/down arrow in the corner) somewhere that they are. I wondered for a while why the sidebar was blank.

**Comment by nodiscc** [comment]
Might as well move `Tags` above `Programming languages` since it's likely it will be more used, it should be more prominent.

**Comment by n8225** [comment]
PR #5 Added a down arrow and uncollapsed the menu by default on desktop.  It will still be collapsed on mobile though.

I left tags below programming languages since it will pretty much hide programming languages on most screens.

**Comment by nodiscc** [comment]
> left tags below programming languages since it will pretty much hide programming languages on most screens.

Currently Tags are hidden on most screens though, and it's likely most users will want to search by tags, not language. That's why I suggested moving it above the other.

> Added a down arrow and uncollapsed the menu by default on desktop

Nice

**Comment by nodiscc** [comment]
Fixed, thank you!
