### ISSUE TITLE
Too much whitespace/layout doesn't let you see many entries on screen

### ISSUE THREAD

**Issue by nodiscc** [n8225/awesome-selfhosted-gen#2]
With the current layout, only 2 or 3 entries are visible on screen at any given time on mobile or moderately small desktop/laptop monitor.

![screen](https://user-images.githubusercontent.com/3950390/50796402-482ac600-12c9-11e9-8b33-384aa53d652f.png)

On https://github.com/Kickball/awesome-selfhosted you can easily see 10-20 entries on screen at any given time.

You don't need to go that extreme, but having 5-10 entries fit on-screen would be an improvement , I think.

Some ideas for improvements:
 - [ ] Decrease font size/heading size/padding/margins a bit
 - [ ] Use only symbolic icons for created/update/source code/website fields
 - [ ] Use smaller icons (star, source code/website)
 - [ ] This would allow putting all the metadata on a single line
 - [ ] Hide non-essential data (creation date?) in a :information_source: tooltip in the heading bar

**Comment by n8225** [comment]
The latest commit should resolve this.

**Comment by nodiscc** [comment]
It does, thanks a lot
